### ISSUE TITLE
Problema de incompatibilidad en "settings.gradle"

### ISSUE THREAD

**Issue by LuIs-Dxd** [difo23/contador_app#12]
### >FAILURE: Build failed with an exception.

>* Where:
>Settings file 'C:\Users\Acer P-Helios\Desktop\React-Native-Project\ReactContador\contador_app-main\android\settings.gradle'

>* What went wrong:
>Could not compile settings file 'C:\Users\Acer P-Helios\Desktop\React-Native-Project\ReactContador\contador_app-main\android\settings.gradle'.

**startup failed:
  General error during semantic analysis: Unsupported class file major version 61**

> 
>   java.lang.IllegalArgumentException: Unsupported class file major version 61
>         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
>         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
>         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
>         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
>         at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
>         at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
>         at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
>         at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
>         at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
>         at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
>         at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
>         at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:79)
>         at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:70)
>         at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:57)
>         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode$2.get(DecompiledClassNode.java:234)
>         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode$2.get(DecompiledClassNode.java:231)
>         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.createMethodNode(DecompiledClassNode.java:242)
>         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:199)
>         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:122)
>         at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:912)
>         at org.codehaus.groovy.ast.ClassNode.tryFindPossibleMethod(ClassNode.java:1280)
>         at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:252)
>         at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:113)
>         at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:142)
>

**Comment by LuIs-Dxd** [comment]
Muchas veces esto pasa porque la versión del build.gradle. No es la misma que la del gradle-wrapper.properties.
en dado caso, la versión del proyecto (que funciona y esta probada)

>    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

**Comment by LuIs-Dxd** [comment]
en dado caso que no funcione, pueden intentar actualizarla "manualmente" y se puede revisar en el gradle-wrapper.properties. En la siguiente linea de codigo, se muestra la versiona actual que tiene tu proyecto, solo tienes que cambiar el "VERSION" por la versión requerida:

distributionUrl=https\://services.gradle.org/distributions/gradle-VERSION-all.zip
